language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
# Using xvfb to Run Tests That Require a GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - python beads_draw_maker.py ./test/flower.txt
  - ls -la image.pdf
  - python beads_draw_maker.py ./test/heart.txt
  - ls -la image.pdf